import pygame as pg
import os

board_height = 600
board_width  = 600

lightSquareColor = (162, 162, 162)
darkSquareColor  = (98, 98, 98)

lightSquareColorSelected = (162, 162, 192)
darkSquareColorSelected  = (98, 98, 128)

bh = int(board_height / 8)
bw = int(board_width / 8)

imagePiecesSet = 'piece_set_2'

black_king_img   = pg.image.load(os.path.join('Images', imagePiecesSet, 'bking.png'))
black_queen_img  = pg.image.load(os.path.join('Images', imagePiecesSet, 'bqueen.png'))
black_rook_img   = pg.image.load(os.path.join('Images', imagePiecesSet, 'brook.png'))
black_bishop_img = pg.image.load(os.path.join('Images', imagePiecesSet, 'bbishop.png'))
black_knight_img = pg.image.load(os.path.join('Images', imagePiecesSet, 'bknight.png'))
black_pawn_img   = pg.image.load(os.path.join('Images', imagePiecesSet, 'bpawn.png'))

white_king_img   = pg.image.load(os.path.join('Images', imagePiecesSet, 'wking.png'))
white_queen_img  = pg.image.load(os.path.join('Images', imagePiecesSet, 'wqueen.png'))
white_rook_img   = pg.image.load(os.path.join('Images', imagePiecesSet, 'wrook.png'))
white_bishop_img = pg.image.load(os.path.join('Images', imagePiecesSet, 'wbishop.png'))
white_knight_img = pg.image.load(os.path.join('Images', imagePiecesSet, 'wknight.png'))
white_pawn_img   = pg.image.load(os.path.join('Images', imagePiecesSet, 'wpawn.png'))


black_king_img   = pg.transform.scale(black_king_img, (bw, bh))
black_queen_img  = pg.transform.scale(black_queen_img, (bw, bh))
black_rook_img   = pg.transform.scale(black_rook_img, (bw, bh))
black_bishop_img = pg.transform.scale(black_bishop_img, (bw, bh))
black_knight_img = pg.transform.scale(black_knight_img, (bw, bh))
black_pawn_img   = pg.transform.scale(black_pawn_img, (bw, bh))

white_king_img   = pg.transform.scale(white_king_img, (bw, bh))
white_queen_img  = pg.transform.scale(white_queen_img, (bw, bh))
white_rook_img   = pg.transform.scale(white_rook_img, (bw, bh))
white_bishop_img = pg.transform.scale(white_bishop_img, (bw, bh))
white_knight_img = pg.transform.scale(white_knight_img, (bw, bh))
white_pawn_img   = pg.transform.scale(white_pawn_img, (bw, bh))


TO_ALG = dict()
TO_ALG[0] = "A1"
TO_ALG[1] = "B1"
TO_ALG[2] = "C1"
TO_ALG[3] = "D1"
TO_ALG[4] = "E1"
TO_ALG[5] = "F1"
TO_ALG[6] = "G1"
TO_ALG[7] = "H1"
TO_ALG[8] = "A2"
TO_ALG[9] = "B2"
TO_ALG[10] = "C2"
TO_ALG[11] = "D2"
TO_ALG[12] = "E2"
TO_ALG[13] = "F2"
TO_ALG[14] = "G2"
TO_ALG[15] = "H2"
TO_ALG[16] = "A3"
TO_ALG[17] = "B3"
TO_ALG[18] = "C3"
TO_ALG[19] = "D3"
TO_ALG[20] = "E3"
TO_ALG[21] = "F3"
TO_ALG[22] = "G3"
TO_ALG[23] = "H3"
TO_ALG[24] = "A4"
TO_ALG[25] = "B4"
TO_ALG[26] = "C4"
TO_ALG[27] = "D4"
TO_ALG[28] = "E4"
TO_ALG[29] = "F4"
TO_ALG[30] = "G4"
TO_ALG[31] = "H4"
TO_ALG[32] = "A5"
TO_ALG[33] = "B5"
TO_ALG[34] = "C5"
TO_ALG[35] = "D5"
TO_ALG[36] = "E5"
TO_ALG[37] = "F5"
TO_ALG[38] = "G5"
TO_ALG[39] = "H5"
TO_ALG[40] = "A6"
TO_ALG[41] = "B6"
TO_ALG[42] = "C6"
TO_ALG[43] = "D6"
TO_ALG[44] = "E6"
TO_ALG[45] = "F6"
TO_ALG[46] = "G6"
TO_ALG[47] = "H6"
TO_ALG[48] = "A7"
TO_ALG[49] = "B7"
TO_ALG[50] = "C7"
TO_ALG[51] = "D7"
TO_ALG[52] = "E7"
TO_ALG[53] = "F7"
TO_ALG[54] = "G7"
TO_ALG[55] = "H7"
TO_ALG[56] = "A8"
TO_ALG[57] = "B8"
TO_ALG[58] = "C8"
TO_ALG[59] = "D8"
TO_ALG[60] = "E8"
TO_ALG[61] = "F8"
TO_ALG[62] = "G8"
TO_ALG[63] = "H8"

TO_NUM = dict()
TO_NUM["A1"] = 0
TO_NUM["B1"] = 1
TO_NUM["C1"] = 2
TO_NUM["D1"] = 3
TO_NUM["E1"] = 4
TO_NUM["F1"] = 5
TO_NUM["G1"] = 6
TO_NUM["H1"] = 7
TO_NUM["A2"] = 8
TO_NUM["B2"] = 9
TO_NUM["C2"] = 10
TO_NUM["D2"] = 11
TO_NUM["E2"] = 12
TO_NUM["F2"] = 13
TO_NUM["G2"] = 14
TO_NUM["H2"] = 15
TO_NUM["A3"] = 16
TO_NUM["B3"] = 17
TO_NUM["C3"] = 18
TO_NUM["D3"] = 19
TO_NUM["E3"] = 20
TO_NUM["F3"] = 21
TO_NUM["G3"] = 22
TO_NUM["H3"] = 23
TO_NUM["A4"] = 24
TO_NUM["B4"] = 25
TO_NUM["C4"] = 26
TO_NUM["D4"] = 27
TO_NUM["E4"] = 28
TO_NUM["F4"] = 29
TO_NUM["G4"] = 30
TO_NUM["H4"] = 31
TO_NUM["A5"] = 32
TO_NUM["B5"] = 33
TO_NUM["C5"] = 34
TO_NUM["D5"] = 35
TO_NUM["E5"] = 36
TO_NUM["F5"] = 37
TO_NUM["G5"] = 38
TO_NUM["H5"] = 39
TO_NUM["A6"] = 40
TO_NUM["B6"] = 41
TO_NUM["C6"] = 42
TO_NUM["D6"] = 43
TO_NUM["E6"] = 44
TO_NUM["F6"] = 45
TO_NUM["G6"] = 46
TO_NUM["H6"] = 47
TO_NUM["A7"] = 48
TO_NUM["B7"] = 49
TO_NUM["C7"] = 50
TO_NUM["D7"] = 51
TO_NUM["E7"] = 52
TO_NUM["F7"] = 53
TO_NUM["G7"] = 54
TO_NUM["H7"] = 55
TO_NUM["A8"] = 56
TO_NUM["B8"] = 57
TO_NUM["C8"] = 58
TO_NUM["D8"] = 59
TO_NUM["E8"] = 60
TO_NUM["F8"] = 61
TO_NUM["G8"] = 62
TO_NUM["H8"] = 63
